# NUMPY KURSU
  • Bu kurs veri analizi bootcamp kapsamında tamamlanmıştır.

In [3]:
#Numpy kütüphanesi daha efektif çalışması açısından C dilinde yazılmıştır.
import numpy as np

In [422]:
x = np.array([1,2,3,4]) #Numpy arraylerinde tek tip veri bulunur. Bu bir sayı öbeği row ve cloumn mantığı yok.
x

array([1, 2, 3, 4])

In [7]:
type(x)

numpy.ndarray

In [9]:
y = np.array([1,2,"3"]) #string data casting.
y
type(y)

numpy.ndarray

In [50]:
z = np.array([2.7,2,3,4,5,6], dtype="int32")
z

array([2, 2, 3, 4, 5, 6])

In [56]:
t = np.array([1,2,3,4,5], dtype = "str")
t

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [64]:
u = np.zeros(5)
u

array([0., 0., 0., 0., 0.])

In [66]:
type(u)

numpy.ndarray

In [68]:
np.zeros(10, dtype="str")

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [72]:
np.zeros((3,4,5,6))

array([[[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
        

In [74]:
np.zeros(10, dtype="bool")

array([False, False, False, False, False, False, False, False, False,
       False])

In [76]:
np.full((2,3), 4)

array([[4, 4, 4],
       [4, 4, 4]])

In [78]:
np.full(2,True)

array([ True,  True])

In [80]:
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [82]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

In [86]:
np.linspace(1,2,3) #linspace means "linear space" (doğrusal aralık) 

array([1. , 1.5, 2. ])

In [88]:
np.linspace(1,2,num=3)

array([1. , 1.5, 2. ])

In [90]:
np.linspace(1,2,3, endpoint=False)

array([1.        , 1.33333333, 1.66666667])

In [92]:
np.random.normal(0,1,(4,5))

array([[-0.93952799,  0.01673072, -1.88902046, -0.70008724, -0.06513635],
       [-1.86144471, -0.03791456, -2.25136472,  0.75190963,  0.75282672],
       [-1.96628117,  1.59189926,  0.9396166 , -0.10714574,  0.90218008],
       [ 0.20833597,  0.58394431,  1.06416446,  1.22497119, -0.8648219 ]])

In [94]:
np.random.normal(0,10,(4,5))

array([[ 11.59652062,   9.15003932,  12.52722199,  -4.73573193,
         -8.25647743],
       [-18.73978201,   2.84598956,   0.71654394,   4.33348316,
         13.11958096],
       [ -5.19552127,  -9.68038936,   8.32689921,  -2.92663525,
          0.97539855],
       [  0.56821069,  -5.03884372,   0.14062204,  -2.54050485,
         -8.55957744]])

In [96]:
np.random.normal(15,10,(4,5)) 

array([[10.4378949 , 17.54427341, 15.25323121, 31.38291024, -5.10964548],
       [25.26202198, 24.43601551, 33.04099885,  9.72571853, 12.66482762],
       [ 0.30786571, 26.90282208, 21.18161563, 17.8073792 , 15.35797795],
       [40.13103499, 17.81137364, 15.98118428, 14.44844432, 26.29042827]])

In [110]:
np.random.randint(1,23)

16

In [108]:
np.random.randint(1,23,(2,5))

array([[22,  4,  3, 14,  5],
       [ 9,  4, 18, 15, 11]])

In [118]:
how_many = {}

for _ in range(200000):
    value = np.random.randint(1,23)
    if value not in how_many:
        how_many[value] = 1
    else:
        how_many[value] +=1
how_many

{18: 9239,
 17: 9268,
 13: 9037,
 11: 9117,
 15: 9087,
 21: 8956,
 10: 9232,
 19: 9139,
 7: 9089,
 3: 8933,
 1: 9082,
 22: 9064,
 4: 9158,
 2: 9090,
 6: 8998,
 5: 9230,
 9: 9035,
 12: 9075,
 16: 9154,
 14: 8995,
 20: 8973,
 8: 9049}

In [124]:
np.eye(5,5) #İdentity(birim) matrix oluşturmaya yarar.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
x1 = np.array([1,2,3])
y1 = np.array([1,2,3])
x1 * y1

array([1, 4, 9])

In [21]:
x1 * 3

array([3, 6, 9])

# array attributes

In [29]:
my_arr = np.array([[1,2,3],[2,3,4]])
my_arr

array([[1, 2, 3],
       [2, 3, 4]])

In [38]:
my_arr.shape

(2, 3)

In [42]:
my_arr.ndim #kaç boyutlu olduğu

2

In [44]:
my_arr.size

6

In [48]:
my_arr.dtype

dtype('int32')

In [52]:
my_arr2 = np.arange(1,11)
my_arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
my_arr2.reshape(2,5) #shape çarpımı size a eşit olmazsa hata alırım.

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [58]:
my_arr.size

6

In [64]:
my_arr.reshape(-1,2) #Burada -1 değeri şu anlama gelir: x * 2 = array.size. x'i otomatik bulur numpy.

array([[1, 2],
       [3, 2],
       [3, 4]])

----------------------------------------------

In [72]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
a[np.newaxis, :]   #Bir tane row, 10 tane column olan bir yapıya çevirdi.

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [76]:
a[: , np.newaxis]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [78]:
a[None, :] #np, newaxis ile aynı işlemi yapar

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [80]:
a[:, None] #np, newaxis ile aynı işlemi yapar

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

# concatenation

In [204]:
a = np.array([1,2,3])

In [86]:
b = np.array([4,5,6])

In [88]:
a + b

array([5, 7, 9])

In [108]:
np.concatenate([a,b]).reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [110]:
my_list = [7,8,9]

In [112]:
np.concatenate([a,b,my_list])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# size mismatch

In [117]:
a = np.array([1,2,3])

In [119]:
x = np.array([[4,5,6],[7,8,9]])

In [123]:
np.concatenate([a,x])  #Dimensionları farklı olduğu için hata alırım.

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [125]:
np.concatenate([x,x])

array([[4, 5, 6],
       [7, 8, 9],
       [4, 5, 6],
       [7, 8, 9]])

In [141]:
np.concatenate([x,x], axis=0).shape # axis=0 dikey doğrultuda birleştirme anlamına gelir.

array([[4, 5, 6],
       [7, 8, 9],
       [4, 5, 6],
       [7, 8, 9]])

In [135]:
np.concatenate([x,x], axis = 1) # axis=1 yatay doğrultuda birleştirme anlamına gelir.

array([[4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [149]:
np.concatenate([a,b], axis=0)

array([1, 2, 3, 4, 5, 6])

In [155]:
np.concatenate([a,b], axis=1) #axis=1 dediğimizde hata alırız. Çünkü numeric dizi bunlar, dimension a sahip değiller.

AxisError: axis 1 is out of bounds for array of dimension 1

In [167]:
np.stack([a,b])  #şimdi hata almadım. Çünkü stack yeni dimension yaratıp onun üzerinde ekleme yapıyor.

array([[1, 4],
       [2, 5],
       [3, 6]])

# splitting
Arrayleri, listeleri bölmeye yarar, sonuç array olarak döner.

In [173]:
my_list = [1,2,3,4,5,6,7,8,9,10]

In [187]:
np.split(my_list, [2])

[array([1, 2]), array([ 3,  4,  5,  6,  7,  8,  9, 10])]

In [189]:
np.split(my_list, [2,5])

[array([1, 2]), array([3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [195]:
np.split(a, [2])

[array([1, 2]), array([3])]

In [198]:
# Splitin sonucunu birden çok değere eşitleme 

In [206]:
a_int, b_int = (1,2)

In [214]:
a_arr , b_arr = np.split(a, [2])
a, a_arr, b_arr

(array([1, 2, 3]), array([1, 2]), array([3]))

# vsplit

In [226]:
t = np.arange(15).reshape(5,3)
t

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [228]:
np.vsplit(t, [1])   #rowları index olarak sayar.

[array([[0, 1, 2]]),
 array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])]

# hsplit 

In [238]:
np.hsplit(t, [1])  #cloumnları index olarak sayar.

[array([[ 0],
        [ 3],
        [ 6],
        [ 9],
        [12]]),
 array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11],
        [13, 14]])]

# sorting

In [276]:
t = np.array([1,5,3,1,4543,12,14])

In [278]:
t = t.reshape(1,t.size)

In [280]:
t

array([[   1,    5,    3,    1, 4543,   12,   14]])

In [292]:
np.sort(t) #inplace etmez yani t aynı kalır

array([[   1,    1,    3,    5,   12,   14, 4543]])

In [294]:
t

array([[   1,    5,    3,    1, 4543,   12,   14]])

In [296]:
t.sort() # inplace eder yani t = np.sort(t) ifadesine eş değer

In [298]:
t

array([[   1,    1,    3,    5,   12,   14, 4543]])

# argsort

In [302]:
t = np.array([1,5,3,1,4543,12,14])

In [306]:
np.argsort(t) # t'yi sıralar ama  küçükten büyüğe sıralanmış şeylerin indexlerini verir.

array([0, 3, 2, 1, 5, 6, 4], dtype=int64)

# multidimensional arraylerde indexleme
Ne kadar boyut varsa bir elemanın konumunu bulmak için o kadar bilgi vermek lazım.

In [330]:
md_array = np.arange(1,21).reshape(4,5)
md_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [347]:
md_array[0]

array([1, 2, 3, 4, 5])

In [349]:
md_array[1,2]

8

In [357]:
md_array[1,2] = 3 #arrayyler mutabledır.

In [353]:
md_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  3,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [355]:
md_array[0:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  3,  9, 10]])

In [359]:
md_array[:,2]

array([ 3,  3, 13, 18])

# fancy indexing
Birbirinden bağımsız farklı indexteki elemanları getirmeye yarar.

In [399]:
x = np.arange(1,16).reshape(5,3)

In [401]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [407]:
idxs = [2,4]  #İstediğimiz index öbekleri
idxs2 = [0,2]

In [411]:
x[idxs]  

array([[ 7,  8,  9],
       [13, 14, 15]])

In [415]:
x[idxs,idxs2]  # [2,0] ve [4,2] indexlerindeki değerleri verir.

array([ 7, 15])

In [417]:
x[idxs]  = 0

In [419]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  0,  0],
       [10, 11, 12],
       [ 0,  0,  0]])

In [439]:
a=np.arange(1,13).reshape(3,4) 
b=a[1,(1,3)] 
b.ndim

1

# subarray

In [452]:
arr = np.arange(1,21).reshape(4,5)

In [454]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [462]:
sub_arr = arr[:2,:3]
sub_arr

array([[1, 2, 3],
       [6, 7, 8]])

In [464]:
sub_arr[0,0] = 100

In [466]:
arr #sub_arr ve arr belleğin aynı yerini kullanır.

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

In [468]:
sub_arr

array([[100,   2,   3],
       [  6,   7,   8]])

In [472]:
copy_arr = arr[:2,:3].copy()
copy_arr

array([[100,   2,   3],
       [  6,   7,   8]])

In [476]:
copy_arr[0,0]

100

In [478]:
copy_arr[0,0] = 1

In [480]:
arr

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

In [482]:
copy_arr

array([[1, 2, 3],
       [6, 7, 8]])

# conditional indexing

In [489]:
a = np.arange(1,11)

In [491]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [496]:
a < 5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [498]:
a[a<5]

array([1, 2, 3, 4])

In [525]:
filt = a < 5

In [527]:
a[filt]

array([1, 2, 3, 4])

In [537]:
b = np.array([2,3,4,5,7,8,96,88,9,1])

In [539]:
a == b

array([False, False, False, False, False, False, False, False,  True,
       False])

In [541]:
a[a==b]

array([9])

In [543]:
(a<3) or (a>5) #and, or condition sözcüklerini numpyda bu amaçla kullanamıyoruz  

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [545]:
(a<3) | (a>5)

array([ True,  True, False, False, False,  True,  True,  True,  True,
        True])

In [547]:
filt = (a<3) | (a>5)

In [549]:
a[filt]

array([ 1,  2,  6,  7,  8,  9, 10])

In [551]:
#filtrenin değili

In [553]:
a[not filt]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [557]:
a[~filt] #tilda işareti ile bir filtrenin değilini alabiliriz

array([3, 4, 5])

In [559]:
a = np.arange(20).reshape(4,5)

In [561]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [563]:
a < 7

array([[ True,  True,  True,  True,  True],
       [ True,  True, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [565]:
a == None

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

# sum

In [580]:
a = np.arange(1,21).reshape(4,5)

In [582]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [584]:
np.sum(a)

210

In [598]:
filt = a < 5

In [600]:
a[filt]

array([1, 2, 3, 4])

In [608]:
np.sum(a[filt])

10

In [624]:
filt = (a>2) & (a<5)

In [626]:
a[filt]

array([3, 4])

In [628]:
np.sum(a[filt])

7

In [639]:
np.sum(a, axis = 0)

array([34, 38, 42, 46, 50])

In [648]:
my_array = np.array([ [1, 2], [3, 4] ])

np.prod(my_array, axis = 0)            #Output : [3 8], prod ile çarpımlarını alırız.
np.prod(my_array, axis = 1)            #Output : [ 2 12]

array([ 2, 12])

# all
Tüm elemanların verilen şartı sağlayıp sağlamadığına bakar.

In [652]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [654]:
a > -1

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [658]:
np.all(a>-1)

True

In [660]:
np.all(a>5)

False

In [680]:
(a>5)

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [676]:
np.all(a>5, axis=1)

array([False,  True,  True,  True])

In [678]:
np.all(a>5, axis=0)

array([False, False, False, False, False])

# any
Herhangi bir elemanın verilen şartı sağlayıp sağlamadığına bakar.

In [685]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [687]:
np.any(a>10)

True

In [689]:
np.any(a>10, axis=1)

array([False, False,  True,  True])

In [691]:
np.any(a>10,axis=0)

array([ True,  True,  True,  True,  True])